//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Posts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facebook_Posts()
        {
            this.Social_Content_Post = new HashSet<Social_Content_Post>();
        }
    
        public System.Guid ID { get; set; }
        public string Message { get; set; }
        public string FromName { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string FromUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Social_Content_Post> Social_Content_Post { get; set; }
    }
}
