//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Social_Contents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Social_Contents()
        {
            this.Social_Content_Post = new HashSet<Social_Content_Post>();
            this.Social_Content_Post1 = new HashSet<Social_Content_Post>();
            this.Social_Location_More = new HashSet<Social_Location_More>();
            this.Social_Contents1 = new HashSet<Social_Contents>();
        }
    
        public System.Guid ID { get; set; }
        public string Text { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public Nullable<bool> IsParent { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Social_Content_Post> Social_Content_Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Social_Content_Post> Social_Content_Post1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Social_Location_More> Social_Location_More { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Social_Contents> Social_Contents1 { get; set; }
        public virtual Social_Contents Social_Contents2 { get; set; }
    }
}
