//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Social_Content_Post
    {
        public System.Guid ID { get; set; }
        public System.Guid PostID { get; set; }
        public Nullable<System.Guid> ContentID { get; set; }
        public Nullable<System.Guid> MatchContentID { get; set; }
        public Nullable<bool> IsChecked { get; set; }
    
        public virtual Facebook_Posts Facebook_Posts { get; set; }
        public virtual Social_Contents Social_Contents { get; set; }
        public virtual Social_Contents Social_Contents1 { get; set; }
    }
}
