//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialDataLocalEntities : DbContext
    {
        public SocialDataLocalEntities()
            : base("name=SocialDataLocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Facebook_Posts> Facebook_Posts { get; set; }
        public virtual DbSet<Social_Content_Post> Social_Content_Post { get; set; }
        public virtual DbSet<Social_Contents> Social_Contents { get; set; }
        public virtual DbSet<Social_Location_More> Social_Location_More { get; set; }
    }
}
